# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run continuous integration
      run: npm ci
    - name: Run eslint
      run: npm run lint
    - name: Build Docker Image
      run: docker build -t mattdonatelli/kazubot:${GITHUB_SHA:0:7} -t mattdonatelli/kazubot:latest .
    - uses: secrethub/actions/env-export@v0.1.0
      env:
        SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
        DOCKER_USERNAME: secrethub://mattdonatelli/kazubot/docker/username
        DOCKER_PASSWORD: secrethub://mattdonatelli/kazubot/docker/password
        SECRETHUB_TOKEN_PATH: mattdonatelli/kazubot/lab/token
    - name: Run Docker and Tests
      run: docker run -e SCRIPT="test" -e SECRETHUB_CREDENTIAL=${{ secrets.SECRETHUB_CREDENTIAL }} -e SECRETHUB_TOKEN_PATH="mattdonatelli/kazubot/lab/token" -- mattdonatelli/kazubot:${GITHUB_SHA:0:7}
    - name: Publish Docker image unique
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push mattdonatelli/kazubot:${GITHUB_SHA:0:7}
    - name: Publish Docker image as latest
      run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push mattdonatelli/kazubot:latest
